insert into pia_ua.cf_noi_portal (

  "Ref No"                             ,
  "NOI ID"                             ,
  "PIANOI Ref"                         ,
  "City"                               ,
  "FEx/PN"                             ,
  "NOI Status"                         ,
  "Last Automation Status Change"      ,
  "NOI Start Date"                     ,
  "NOI Expiry Date"                    ,
  "NOI Automation Type"                ,
  "NOI Automation Status"              ,
  "CP Reference"                       ,
  "Workflow"                           ,
  "Region"                             ,
  "Raised By"                          ,
  "NOI Extension Count"                ,
  "Primary/Additional"                 ,
  "DR Status"                          ,
  "Build Complete Status"              ,
  "Build Complete Submission Date"     ,
  "Build Complete Raised By"           ,
  "Build Complete Sabor Ref"           ,
  "Build Complete Acceptance Date"     
)
select
  "Ref No"                             ,
  "NOI ID"                             ,
  "PIANOI Ref"                         ,
  "City"                               ,
  "FEx/PN"                             ,
  "NOI Status"                         ,
  "Last Automation Status Change"      ,
  "NOI Start Date"                     ,
  "NOI Expiry Date"                    ,
  "NOI Automation Type"                ,
  "NOI Automation Status"              ,
  "CP Reference"                       ,
  "Workflow"                           ,
  "Region"                             ,
  "Raised By"                          ,
  "NOI Extension Count"                ,
  "Primary/Additional"                 ,
  "DR Status"                          ,
  "Build Complete Status"              ,
  "Build Complete Submission Date"     ,
  "Build Complete Raised By"           ,
  "Build Complete Sabor Ref"           ,
  "Build Complete Acceptance Date"   

from pia_raw.cf_noi_portal ;  